_extends: .github:_opensource.yaml

repository:
  name: organization-membership-action
  description: Manage your Github organization/teams membership with pull requests!
  topics: github, actions, management
