_extends: .github:.github/_opensource.yml

repository:
  name: organization-membership-action
  description: Manage your Github organization/teams membership with pull requests!
  topics: github, actions, management

labels:
  - name: dependencies
    color: '#70f9e0'
    description: Update dependencies

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ['Check']
      required_signatures: true
      enforce_admins: true
      restrictions: null
